# Generated by Django 3.2.23 on 2024-02-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_customstudent_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstudent',
            name='profile_img',
            field=models.ImageField(default='', upload_to='student_profile/'),
        ),
    ]
