# Generated by Django 3.2.23 on 2024-02-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0004_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customteacher',
            name='profile_img',
            field=models.ImageField(default='', upload_to='teacher_profile/'),
        ),
    ]
