# Generated by Django 3.2.23 on 2024-03-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize_app', '0003_studentanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
